name: Talk

on:
  workflow_dispatch:
    inputs:
      content:
        description: "内容"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update posts
        run: |
          FILE=posts.json

          if [ ! -f $FILE ]; then
            echo "[]" > $FILE
          fi

          CONTENT="${{ github.event.inputs.content }}"
          TIME=$(date +"%Y-%m-%d %H:%M:%S")

          jq ". += [{\"content\": \"$CONTENT\", \"time\": \"$TIME\"}]" $FILE > temp.json
          mv temp.json $FILE

      - name: Commit
        run: |
          git config user.name "akira"
          git config user.email "akira@example.com"
          git add posts.json
          git commit -m "update talk" || echo "no changes"
          git push
